model: gt
hidden_channels: 64
mlp_hidden_channels: 64
num_layers: 3
num_heads: 4
gated_residual: True
with_feedforwards: True
norm_edges: True
rel_pos_emb: True
accept_adjacency_matrix: True
lr: 0.00005
lr_decay: 0.999
batch_size: 128
max_norm: 5.0
optimizer: 'adamw'
momentum: 0.9
pool: 'c'
smooth_loss: True
triplets_per_anchor: 16
distance: 'snr'
alpha: 1.0
gamma: 4.022879258650723
beta: 0.6120957227224214
margin: 1.906408074987083
same_halogen_negative: True
